echemdb/svgdigitizer

svgdigitizer/svgdigitizer.py

fixed path detection

---

svgdigitizer/electrochemistry/cv.py

The class now requires metadata (dict) and an SVGPlot class.
It should work with the following code when you change the path to the files accordingly:
```python
import yaml
from svgdigitizer.svgplot import SVGPlot
from svgdigitizer.electrochemistry.cv import CV
yamlfile = 'digitizer/test/data/xy.yaml'
with open(yamlfile) as f:
metadata = yaml.load(f, Loader=yaml.FullLoader)
svgplot = SVGPlot('digitizer/test/data/xy.svg', xlabel='U', ylabel='I')
cv = CV(metadata=metadata, SVGPlot=svgplot)
cv.svgplot.plot()
cv.plot_cv()
```

Modified init of electrochemistry.cv.CV

---

README.md

A short description of the commands. 
I am not sure how many details this part should contain. At the moment I have the impression that it is not intuitive, especially since it is not completely clear where to start and how a possible SVG file should look like.

Update readme of the API

---

svgdigitizer/electrochemistry/cv.py

Added a short docu on `def x_label()`

Fixed cv.plot()

---

.github/workflows/doc.yml

I made these changes manually to the gh-pages branch and it seems to work.

deploy svgdigitizer docs to svgdigitizer not to svgdigitizer/svgdigitizer

---

svgdigitizer/electrochemistry/cv.py

Includes primarily mA conversion typos.

Added more typos to the cv module

---

svgdigitizer/__main__.py

without this change, there is an error that the directory `""` cannot be found.

Fix svgdigitizer cv when invoked on files in the current directory

---

.github/workflows/test.yml

This requires changes in the GitHub setup. I think that this one is completely uncontroversial so I will merge without review once the CI looks good.

Test for Python 3.9 & 3.10

---

.github/workflows/doc.yml
svgdigitizer/__main__.py
svgdigitizer/electrochemistry/cv.py
svgdigitizer/svgplot.py

Add --outdir parameter everywhere

---

README.md
doc/_templates/breadcrumbs.html
doc/api/cv.md
doc/api/svg.md
doc/api/svgplot.md
doc/conf.py
doc/news/edit-on-github.rst
rever.xsh
svgdigitizer/electrochemistry/cv.py

Add Edit on GitHub links

---

setup.py

Add setuptools to setup.py

---

doc/news/setuppython.rst
environment.yml
setup.py

Checklist
Python 3.9 is required to run the module. See also https://github.com/echemdb/echemdb/issues/36.

Fixes the python version to 3.9 in setup.py and environment.yaml

---

doc/news/python39.rst
environment.yml
setup.py

Fix dependency on Python 3.9

---

doc/news/TEMPLATE.rst
doc/news/restore-news.rst

Restore news template

---

doc/news/frictionless-click.rst
setup.py

Require a version of frictionless that cannot depend on an unsupported click

---

.github/pull_request_template.md

Add checkbox `Update docu` to the PR template

---

.github/workflows/doc.yml
.github/workflows/lint.yml
.github/workflows/test.yml
doc/news/workflow.rst
doc/workflow.md
svgdigitizer/electrochemistry/cv.py
svgdigitizer/svgplot.py

Checklist
**Workflow**: Was outdated.
**Doctest**: Adapted to newer version of pytest.
**Linkchecker**: Also due to changes in other repos some links were broken. 
* For some reason `repology` is detected as broken link. But only in the CI and not when I test it locally.

update github workflows, doctests, and broken links

---

doc/news/cv-linked.rst
svgdigitizer/electrochemistry/cv.py

Checklist
Fix detection of `simultaneous measurement` in `electrochemistry.cv` caused by a typo.

Fix detection of `simultaneous measurement` in `electrochemistry.cv`

---

doc/news/package-unit.rst
svgdigitizer/entrypoint.py
test/data/axes_orientation.json.expected
test/data/cv_comment.json.expected
test/data/package.json.expected
test/data/xy_rate.json.expected
test/data/xy_rate_reference.json.expected
test/data/xy_rate_without_metadata.json.expected
test/data/xy_rate_without_metadata_skewed.json.expected

Checklist
* Enable pretty print json files, which should allow finding mistakes more easily.
Fixes: #179

Fix creating datapackages

---

test/data/axes_orientation.json.expected
test/data/cv_bibliography.json.expected
test/data/cv_comment.json.expected
test/data/figure_bibliography.json.expected
test/data/figure_comment.json.expected
test/data/package_no_bibliography.json.expected
test/data/xy_rate.json.expected
test/data/xy_rate_reference.json.expected
test/data/xy_rate_reference_no_si.json.expected
test/data/xy_rate_without_metadata.json.expected
test/data/xy_rate_without_metadata_skewed.json.expected

Checklist -> Not required (see below)
This fixes the output test files according to the latest version of frictionless (5.10.5). This has no impact on the functionalities of the digitizer and hence does not require any news.

fix json output according to frictionless 5.10.5

---

.github/workflows/doc.yml

Checklist
The page won't be published until linkchecker is satisfied. We now check links after publishing, which allows fixing the issues in a next step.

Detect broken links after publishing page.

---

README.md
doc/cli.md
doc/index.md
doc/usage.md
doc/workflow.md

Describe advanced usage with `unitpackage`

---

.github/workflows/test.yml
doc/cli.md
doc/news/pillow10.rst
doc/usage.md
doc/workflow.md
environment.yml
setup.py

Checklist
See https://github.com/advisories/GHSA-j7hp-h8jx-5ppr

Fix pillow vulnerability

---

doc/usage.md
doc/workflow.md

Checklist
A collection of typoes

Fix documentation typoes

---

.github/workflows/doc.yml

Checklist
Ignores linkchecker warnings during build test, which would stop the test with an error.
No news required.

Ignore linkchecker warnings

---

README.md

Fix logo link for display on PyPI

---

.github/workflows/test.yml
doc/news/macos.rst
environment.yml

Enable testing on macOS again

---

.github/workflows/test.yml
doc/news/python3.12.rst

Enable Python 3.12 tests

---

doc/news/dependencies2.rst
doc/news/pyproject.rst
environment.yml
pyproject.toml

Remove unnecessary dependencies

---

environment.yml
rever.xsh

Checklist
Hopefully fixes #207 
changes adapted from https://github.com/flatsurf/cppyythonizations/commit/d40ced6abda1bd35409f9235d67eb7d6b1ea6faa

Change rever config to handle pyproject.toml

---

ChangeLog
README.md

Clean Changelog and update logo URL

---

README.md
doc/index.md

Changed Advantages to Features in the documentation

---

environment.yml

use packages from conda instead of pypi

---

svgdigitizer/svg.py
svgdigitizer/test/cli.py

This needs #220 to be merged first.
Checklist

Add missing doctests

---

pixi.lock

pixi update

---

pixi.lock
pyproject.toml

fix deprecation warning of pixi about version definitions

---

doc/news/wheel_rever.rst
rever.xsh

Wheel rever

---

doc/cli.md
doc/news/svg-from-img.rst
pixi.lock
svgdigitizer/entrypoint.py

Allow to create svg from image directly

---

doc/news/fix-embedded-mimetype.rst
svgdigitizer/entrypoint.py

fix mime type for embedded
